- name: "NOTSCORED | 3.1.1 | PATCH | Ensure IPv6 is disabled"
  lineinfile:
      dest: /etc/default/grub
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.*ipv6.disable)\"[^\"]*)(\".*)'
      replace: '\1 ipv6.disable=1\2'
      follow: true
      backrefs: true
  notify:
      - grub2cfg
  when:
      - not rhel7cis_ipv6_required
      - rhel7cis_rule_3_1_1|bool
  tags:
      - level2
      - notscored
      - patch
      - rule_3.1.1

- name: "NOTSCORED | 3.1.2 | PATCH | Ensure wireless interfaces are disabled"
  command: /bin/true
  changed_when: no
  when:
      - rhel7cis_firewall == "iptables"
      - rhel7cis_rule_3_1_2|bool
  tags:
      - level1
      - level2
      - patch
      - notscored
      - rule_3.1.2
      - notimplemented

- name: "SCORED | 3.2.1 | PATCH | Ensure IP forwarding is disabled"
  block:
      - name: "SCORED | 3.2.1 | PATCH | Ensure IP forwarding is disabled | ipv4"
        sysctl:
            name: net.ipv4.ip_forward
            value: '0'
            state: present
            reload: yes
            ignoreerrors: yes
        notify:
            - sysctl flush ipv4 route table
      - name: "SCORED | 3.2.1 | PATCH | Ensure IP forwarding is disabled | ipv6"
        sysctl:
            name: net.ipv6.ip_forward
            value: '0'
            state: present
            reload: yes
            ignoreerrors: yes
        notify:
            - sysctl flush ipv6 route table
        when:
            - not rhel7cis_ipv6_required
  when:
      - not rhel7cis_is_router
      - rhel7cis_rule_3_2_1|bool
  tags:
      - level1
      - scored
      - sysctl
      - patch
      - rule_3.2.1

- name: "SCORED | 3.2.2 | PATCH | Ensure packet redirect sending is disabled"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  with_items:
      - { name: net.ipv4.conf.all.send_redirects, value: 0 }
      - { name: net.ipv4.conf.default.send_redirects, value: 0 }
  notify:
      - sysctl flush ipv4 route table
  when:
      - not rhel7cis_is_router
      - rhel7cis_rule_3_2_2|bool
  tags:
      - level1
      - scored
      - sysctl
      - patch
      - rule_3.2.2

- name: "SCORED | 3.3.1 | PATCH | Ensure source routed packets are not accepted"
  block:
      - name: "SCORED | 3.3.1 | PATCH | Ensure source routed packets are not accepted | ipv4"
        sysctl:
            name: '{{ item.name }}'
            value: '{{ item.value }}'
            sysctl_set: yes
            state: present
            reload: yes
            ignoreerrors: yes
        with_items:
            - { name: net.ipv4.conf.all.accept_source_route, value: 0 }
            - { name: net.ipv4.conf.default.accept_source_route, value: 0 }
        notify:
            - sysctl flush ipv4 route table
      - name: "SCORED | 3.3.1 | PATCH | Ensure source routed packets are not accepted | ipv6"
        sysctl:
            name: '{{ item.name }}'
            value: '{{ item.value }}'
            sysctl_set: yes
            state: present
            reload: yes
            ignoreerrors: yes
        with_items:
            - { name: net.ipv6.conf.all.accept_source_route, value: 0 }
            - { name: net.ipv6.conf.default.accept_source_route, value: 0 }
        notify:
            - sysctl flush ipv6 route table
        when:
            - not rhel7cis_ipv6_required
  when:
      - rhel7cis_rule_3_3_1|bool
  tags:
      - level1
      - scored
      - sysctl
      - patch
      - rule_3.3.1

- name: "SCORED | 3.3.2 | PATCH | Ensure ICMP redirects are not accepted"
  block:
      - name: "SCORED | 3.3.2 | PATCH | Ensure ICMP redirects are not accepted | ipv4"
        sysctl:
            name: '{{ item.name }}'
            value: '{{ item.value }}'
            sysctl_set: yes
            state: present
            reload: yes
            ignoreerrors: yes
        with_items:
            - { name: net.ipv4.conf.all.accept_redirects, value: 0 }
            - { name: net.ipv4.conf.default.accept_redirects, value: 0 }
        notify:
            - sysctl flush ipv4 route table

      - name: "SCORED | 3.3.2 | PATCH | Ensure ICMP redirects are not accepted | ipv6"
        sysctl:
            name: '{{ item.name }}'
            value: '{{ item.value }}'
            sysctl_set: yes
            state: present
            reload: yes
            ignoreerrors: yes
        with_items:
            - { name: net.ipv6.conf.all.accept_redirects, value: 0 }
            - { name: net.ipv6.conf.default.accept_redirects, value: 0 }
        notify:
            - sysctl flush ipv6 route table
        when:
            - not rhel7cis_ipv6_required
  when:
      - rhel7cis_rule_3_3_2|bool
  tags:
      - level1
      - scored
      - sysctl
      - patch
      - rule_3.3.2

- name: "SCORED | 3.3.3 | PATCH | Ensure secure ICMP redirects are not accepted | ipv4"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  with_items:
      - { name: net.ipv4.conf.all.secure_redirects, value: 0 }
      - { name: net.ipv4.conf.default.secure_redirects, value: 0 }
  notify:
      - sysctl flush ipv4 route table
  when:
      - rhel7cis_rule_3_3_3|bool
  tags:
      - level1
      - scored
      - sysctl
      - patch
      - rule_3.3.3

- name: "SCORED | 3.3.4 | PATCH | Ensure suspicious packets are logged | ipv4"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  with_items:
      - { name: net.ipv4.conf.all.log_martians, value: 1 }
      - { name: net.ipv4.conf.default.log_martians, value: 1 }
  notify:
      - sysctl flush ipv4 route table
  when:
      - rhel7cis_rule_3_3_4|bool
  tags:
      - level1
      - scored
      - sysctl
      - patch
      - rule_3.3.4

- name: "SCORED | 3.3.5 | PATCH | Ensure broadcast ICMP requests are ignored | ipv4"
  sysctl:
      name: net.ipv4.icmp_echo_ignore_broadcasts
      value: '1'
      state: present
      reload: yes
      ignoreerrors: yes
  notify:
      - sysctl flush ipv4 route table
  when:
      - rhel7cis_rule_3_3_5|bool
  tags:
      - level1
      - scored
      - sysctl
      - patch
      - rule_3.3.5

- name: "SCORED | 3.3.6 | PATCH | Ensure bogus ICMP responses are ignored | ipv4"
  sysctl:
      name: net.ipv4.icmp_ignore_bogus_error_responses
      value: '1'
      state: present
      reload: yes
      ignoreerrors: yes
  notify:
      - sysctl flush ipv4 route table
  when:
      - rhel7cis_rule_3_3_6|bool
  tags:
      - level1
      - scored
      - sysctl
      - patch
      - rule_3.3.6

- name: "SCORED | 3.3.7 | PATCH | Ensure Reverse Path Filtering is enabled"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  with_items:
      - { name: net.ipv4.conf.all.rp_filter, value: 1 }
      - { name: net.ipv4.conf.default.rp_filter, value: 1 }
  notify:
      - sysctl flush ipv4 route table
  when:
      - rhel7cis_rule_3_3_7|bool
  tags:
      - level1
      - scored
      - sysctl
      - patch
      - rule_3.3.7

- name: "SCORED | 3.3.8 | PATCH | Ensure TCP SYN Cookies is enabled"
  sysctl:
      name: net.ipv4.tcp_syncookies
      value: 1
      state: present
      reload: yes
      ignoreerrors: yes
  notify:
      - sysctl flush ipv4 route table
  when:
      - rhel7cis_rule_3_3_8|bool
  tags:
      - level1
      - scored
      - sysctl
      - patch
      - rule_3.3.8

- name: "NOTSCORED | 3.3.9 | PATCH | Ensure IPv6 router advertisements are not accepted"
  sysctl:
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      sysctl_set: yes
      state: present
      reload: yes
      ignoreerrors: yes
  with_items:
      - { name: net.ipv6.conf.all.accept_ra, value: 0 }
      - { name: net.ipv6.conf.default.accept_ra, value: 0 }
  notify:
      - sysctl flush ipv6 route table
  when:
      - rhel7cis_ipv6_required | bool
      - rhel7cis_rule_3_3_9|bool
  tags:
      - level1
      - notscored
      - sysctl
      - patch
      - rule_3.3.9

- name: "NOTSCORED | 3.4.1 | PATCH | Ensure DCCP is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install dccp(\\s|$)"
      line: "install dccp /bin/true"
      create: yes
  when:
      - rhel7cis_rule_3_4_1|bool
  tags:
      - level1
      - notscored
      - patch
      - rule_3.4.1

- name: "NOTSCORED | 3.4.2 | PATCH | Ensure SCTP is disabled"
  lineinfile:
      dest: /etc/modprobe.d/CIS.conf
      regexp: "^(#)?install sctp(\\s|$)"
      line: "install sctp /bin/true"
      create: yes
  when:
      - rhel7cis_rule_3_4_2|bool
  tags:
      - level1
      - notscored
      - patch
      - rule_3.4.2

- name: "SCORED | 3.5.1.1 | PATCH | Ensure firewalld is installed"
  yum:
      name: firewalld
      state: present
  when:
      - rhel7cis_rule_3_5_1_1|bool
      - rhel7cis_firewall == "firewalld"
  notify: restart firewalld
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.1.1

- name: "SCORED | 3.5.1.2 | PATCH | Ensure iptables-service package is not installed"
  yum:
      name: iptables-services
      state: absent
  when:
      - rhel7cis_rule_3_5_1_2|bool
      - rhel7cis_firewall == "firewalld"
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.1.2

- name: "SCORED | 3.5.1.3 | PATCH | Ensure nftables is not installed or stopped and masked"
  yum:
      name: nftables
      state: absent
  when:
      - rhel7cis_rule_3_5_1_3|bool
      - rhel7cis_firewall == "firewalld"
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.1.3

- name: "SCORED | 3.5.1.4 | PATCH | Ensure firewalld is enabled and running"
  service:
      name: firewalld
      state: started
      enabled: yes
  when:
      - rhel7cis_rule_3_5_1_4|bool
      - rhel7cis_firewall == "firewalld"
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.1.4

- name: "SCORED | 3.5.1.5 | PATCH | Ensure default zone is set"
  command: "firewall-cmd --set-default-zone={{ rhel7cis_firewall_default_zone }}"
  changed_when: false
  when:
      - rhel7cis_rule_3_5_1_5|bool
      - rhel7cis_firewall == "firewalld"
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.1.5

- name: "SCORED | 3.5.1.6 | PATCH | Ensure network interfaces are assigned to appropriate zone"
  command: /bin/true
  changed_when: no
  when:
      - rhel7cis_firewall == "firewalld"
      - rhel7cis_rule_3_5_1_6|bool
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.1.6
      - notimplemented

- name: "SCORED | 3.5.1.7 | PATCH | Ensure unnecessary services and ports are not accepted"
  command: /bin/true
  changed_when: no
  when:
      - rhel7cis_firewall == "firewalld"
      - rhel7cis_rule_3_5_1_7|bool
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.1.7
      - notimplemented

- name: "SCORED | 3.5.2.1 | Ensure nftables is installed"
  yum:
      name: nftables
      state: present
  when:
      - rhel7cis_firewall == "nftables"
      - rhel7cis_rule_3_5_2_1|bool
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.2.1

- name: "SCORED | 3.5.2.2 | Ensure firewalld is not installed or stopped and masked"
  yum:
      name: firewalld
      state: absent
  when:
      - rhel7cis_firewall == "nftables"
      - rhel7cis_rule_3_5_2_2|bool
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.2.2

- name: "SCORED | 3.5.2.3 | Ensure iptables-services is not installed"
  yum:
      name: iptables-services
      state: absent
  when:
      - rhel7cis_firewall == "nftables"
      - rhel7cis_rule_3_5_2_3|bool
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.2.3

- name: "SCORED | 3.5.2.4 | Ensure iptables are flushed"
  block:

      - name: "SCORED | 3.5.2.4 | Ensure iptables are flushed | ipv4"
        iptables:
            chain: "{{ item }}"
            flush: yes
            ip_version: ipv4
        loop:
            - 'INPUT'
            - 'FORWARD'
            - 'OUTPUT'

      - name: "SCORED | 3.5.2.4 | Ensure iptables are flushed | ipv6"
        iptables:
            chain: "{{ item }}"
            flush: yes
            ip_version: ipv6
        loop:
            - 'INPUT'
            - 'FORWARD'
            - 'OUTPUT'
  when:
      - rhel7cis_firewall == "nftables"
      - rhel7cis_rule_3_5_2_4|bool
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.2.4

- name: "SCORED | 3.5.2.5 | PATCH | Ensure a table exists"
  command: /bin/true
  changed_when: no
  when:
      - rhel7cis_firewall == "nftables"
      - rhel7cis_rule_3_5_2_5|bool
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.2.5
      - notimplemented

- name: "SCORED | 3.5.2.6 | PATCH | Ensure base chains exist"
  command: /bin/true
  changed_when: no
  when:
      - rhel7cis_firewall == "nftables"
      - rhel7cis_rule_3_5_2_6|bool
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.2.6
      - notimplemented

- name: "SCORED | 3.5.2.7 | PATCH | Ensure loopback traffic is configured"
  command: /bin/true
  changed_when: no
  when:
      - rhel7cis_firewall == "nftables"
      - rhel7cis_rule_3_5_2_7|bool
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.2.7
      - notimplemented

- name: "SCORED | 3.5.2.8 | PATCH | Ensure outbound and established connections are configured"
  command: /bin/true
  changed_when: no
  when:
      - rhel7cis_firewall == "nftables"
      - rhel7cis_rule_3_5_2_8|bool
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.2.8
      - notimplemented

- name: "SCORED | 3.5.2.9 | PATCH | Ensure default deny firewall policy"
  command: /bin/true
  changed_when: no
  when:
      - rhel7cis_firewall == "nftables"
      - rhel7cis_rule_3_5_2_9|bool
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.2.9
      - notimplemented

- name: "SCORED | 3.5.2.10 | PATCH | Ensure nftables service is enabled"
  service:
      name: nftables
      enabled: yes
  when:
      - rhel7cis_firewall == "nftables"
      - rhel7cis_rule_3_5_2_10|bool
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.2.10

- name: "SCORED | 3.5.2.11 | PATCH | Ensure nftables rules are permanent"
  command: /bin/true
  changed_when: no
  when:
      - rhel7cis_firewall == "nftables"
      - rhel7cis_rule_3_5_2_11|bool
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.2.11
      - notimplemented

- name: "SCORED | 3.5.3.1.1 | PATCH | Ensure iptables is installed"
  yum:
      name: iptables,iptables-services
      state: present
  when:
      - rhel7cis_firewall == "iptables"
      - rhel7cis_rule_3_5_3_1_1|bool
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.3.1.1

- name: "SCORED | 3.5.3.1.2 | PATCH | Ensure nftables is not installed"
  yum:
      name: nftables
      state: absent
  when:
      - rhel7cis_firewall == "iptables"
      - rhel7cis_rule_3_5_3_1_2|bool
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.3.1.2

- name: "SCORED | 3.5.3.1.3 | PATCH | Ensure firewalld is not installed or stopped and masked"
  yum:
      name: firewalld
      state: absent
  when:
      - rhel7cis_firewall == "iptables"
      - rhel7cis_rule_3_5_3_1_3|bool
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.3.1.3

- name: "SCORED | 3.5.3.2.1 | PATCH | Ensure default deny firewall policy"
  command: /bin/true
  changed_when: no
  when:
      - rhel7cis_firewall == "iptables"
      - rhel7cis_rule_3_5_3_2_1|bool
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.3.2.1
      - notimplemented

- name: "SCORED | 3.5.3.2.2 | PATCH | Ensure loopback traffic is configured"
  command: /bin/true
  changed_when: no
  when:
      - rhel7cis_firewall == "iptables"
      - rhel7cis_rule_3_5_3_2_2|bool
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.3.2.2
      - notimplemented

- name: "NOTSCORED | 3.5.3.2.3 | PATCH | Ensure outbound and established connections are configured"
  command: /bin/true
  changed_when: no
  when:
      - rhel7cis_firewall == "iptables"
      - rhel7cis_rule_3_5_3_2_3|bool
  tags:
      - level1
      - notscored
      - patch
      - rule_3.5.3.2.3
      - notimplemented

- name: "SCORED | 3.5.3.2.4 | PATCH | Ensure firewall rules exist for all open ports"
  command: /bin/true
  changed_when: no
  when:
      - rhel7cis_firewall == "iptables"
      - rhel7cis_rule_3_5_3_2_4|bool
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.3.2.4
      - notimplemented

- name: "SCORED | 3.5.3.2.5 | PATCH | Ensure iptables rules are saved"
  command: /bin/true
  changed_when: no
  when:
      - rhel7cis_firewall == "iptables"
      - rhel7cis_rule_3_5_3_2_5|bool
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.3.2.5
      - notimplemented

- name: "SCORED | 3.5.3.2.6 | PATCH | Ensure iptables is enabled and running"
  service:
      name: iptables
      state: started
      enabled: yes
  when:
      - rhel7cis_firewall == "iptables"
      - rhel7cis_rule_3_5_3_2_6|bool
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.3.2.6

- name: "SCORED | 3.5.3.3.1 | PATCH | Ensure IPv6 default deny firewall policy"
  command: /bin/true
  changed_when: no
  when:
      - rhel7cis_firewall == "iptables"
      - rhel7cis_rule_3_5_3_3_1|bool
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.3.3.1
      - notimplemented

- name: "SCORED | 3.5.3.3.2 | PATCH | Ensure IPv6 loopback traffic is configured"
  command: /bin/true
  changed_when: no
  when:
      - rhel7cis_firewall == "iptables"
      - rhel7cis_rule_3_5_3_3_2|bool
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.3.3.2
      - notimplemented

- name: "NOTSCORED | 3.5.3.3.3 | PATCH | Ensure IPv6 outbound and established connections are configured"
  command: /bin/true
  changed_when: no
  when:
      - rhel7cis_firewall == "iptables"
      - rhel7cis_rule_3_5_3_3_3|bool
  tags:
      - level1
      - notscored
      - patch
      - rule_3.5.3.3.3
      - notimplemented

- name: "SCORED | 3.5.3.3.4 | PATCH | Ensure IPv6 firewall rules exist for all open ports"
  command: /bin/true
  changed_when: no
  when:
      - rhel7cis_firewall == "iptables"
      - rhel7cis_rule_3_5_3_3_4|bool
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.3.3.4
      - notimplemented

- name: "SCORED | 3.5.3.3.5 | PATCH | Ensure IPv6 iptables rules are saved"
  command: /bin/true
  changed_when: no
  when:
      - rhel7cis_firewall == "iptables"
      - rhel7cis_rule_3_5_3_3_5|bool
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.3.3.5
      - notimplemented

- name: "SCORED | 3.5.3.3.6 | PATCH | Ensure IPv6 iptables is enabled and running"
  service:
      name: iptables
      state: started
      enabled: yes
  when:
      - rhel7cis_firewall == "iptables"
      - rhel7cis_rule_3_5_3_3_6|bool
  tags:
      - level1
      - scored
      - patch
      - rule_3.5.3.3.6
