- name: "SCORED | 2.1.1 | PATCH | Ensure xinetd is not installed"
  yum:
      name: xinetd
      state: absent
  when:
      - rhel7cis_rule_2_1_1|bool
      - not rhel7cis_xinetd_required|bool
  tags:
      - level1
      - scored
      - services
      - patch
      - rule_2.1.1

- name: "SCORED | 2.2.1.1 | PATCH | Ensure time synchronization is in use"
  block:
      - name: "SCORED | 2.2.1.1 | PATCH | Ensure time synchronization is in use - service install"
        yum:
            name: "{{ rhel7cis_time_synchronization }}"
            state: present

      - name: "SCORED | 2.2.1.1 | PATCH | Ensure time synchronization is in use - service start"
        service:
            name: "{{ rhel7cis_time_synchronization }}d"
            state: started
            enabled: true

      - name: "SCORED | 2.2.1.1 | PATCH | Ensure time synchronization is in use - service stop ntp"
        service:
            name: "ntpd"
            state: stopped
            enabled: false
        when:
            - rhel7cis_time_synchronization == "chrony"
            - ntpd_service_status.stdout == "loaded"

      - name: "SCORED | 2.2.1.1 | PATCH | Ensure time synchronization is in use - service stop chrony"
        service:
            name: chronyd
            state: stopped
            enabled: false
        ignore_errors: true
        when:
            - rhel7cis_time_synchronization == "ntp"
            - chronyd_service_status.stdout == "loaded"
  when:
      - rhel7cis_rule_2_2_1_1
  tags:
      - level1
      - scored
      - ntp
      - chrony
      - patch
      - rule_2.2.1.1

- name: "SCORED | 2.2.1.2 | PATCH | Ensure chrony is configured"
  template:
      src: chrony.conf.j2
      dest: /etc/chrony.conf
      owner: root
      group: root
      mode: 0644
  when:
      - rhel7cis_time_synchronization == "chrony"
      - rhel7cis_rule_2_2_1_2|bool
  tags:
      - level1
      - patch
      - rule_2.2.1.2

- name: "SCORED | 2.2.1.2 | PATCH | Ensure chrony is configured | modify /etc/sysconfig/chronyd | 1"
  lineinfile:
      dest: /etc/sysconfig/chronyd
      regexp: "^(#)?OPTIONS"
      line: "OPTIONS=\"-u chrony\""
      state: present
      create: yes
  when:
      - rhel7cis_time_synchronization == "chrony"
      - rhel7cis_rule_2_2_1_2|bool
  tags:
      - level1
      - patch
      - rule_2.2.1.2

- name: "SCORED | 2.2.1.3 | PATCH | Ensure ntp is configured | modify /etc/ntp.conf"
  template:
      src: ntp.conf.j2
      dest: /etc/ntp.conf
      owner: root
      group: root
      mode: 0644
  when:
      - rhel7cis_time_synchronization == "ntp"
      - rhel7cis_rule_2_2_1_3|bool
  tags:
      - level1
      - patch
      - rule_2.2.1.3

- name: "SCORED | 2.2.1.3 | PATCH | Ensure ntp is configured | modify /etc/sysconfig/ntpd"
  lineinfile:
      dest: /etc/sysconfig/ntpd
      regexp: "^(#)?OPTIONS"
      line: "OPTIONS=\"-u ntp:ntp\""
  when:
      - rhel7cis_time_synchronization == "ntp"
      - rhel7cis_rule_2_2_1_3|bool
  tags:
      - level1
      - patch
      - rule_2.2.1.3

- name: "SCORED | 2.2.1.3 | PATCH | Ensure ntp is configured | modify /usr/lib/systemd/system/ntpd.service"
  lineinfile:
      dest: /usr/lib/systemd/system/ntpd.service
      regexp: "^(#)?ExecStart"
      line: "ExecStart=/usr/sbin/ntpd -u ntp:ntp $OPTIONS"
  when:
      - rhel7cis_time_synchronization == "ntp"
      - rhel7cis_rule_2_2_1_3|bool
  tags:
      - level1
      - patch
      - rule_2.2.1.3

- name: "SCORED | 2.2.2 | PATCH | Ensure X11 Server components are not installed"
  yum:
      name: xorg-x11-server*
      state: absent
  when:
      - rhel7cis_rule_2_2_2|bool
      - not rhel7cis_xwindows_required
  tags:
      - level1
      - patch
      - scored
      - rule_2.2.2

- name: "SCORED | 2.2.3 | PATCH | Ensure Avahi Server is not installed"
  yum:
      name: avahi-autoipd,avahi
      state: absent
  when:
      - not rhel7cis_avahi_server
      - rhel7cis_rule_2_2_3|bool
  tags:
      - level1
      - scored
      - avahi
      - services
      - patch
      - rule_2.2.3

- name: "SCORED | 2.2.4 | PATCH | Ensure CUPS is not installed"
  yum:
      name: cups
      state: absent
  when:
      - not rhel7cis_cups_server
      - rhel7cis_rule_2_2_4|bool
  tags:
      - level1
      - scored
      - cups
      - services
      - patch
      - rule_2.2.4

- name: "SCORED | 2.2.5 | PATCH | Ensure DHCP Server is not installed"
  yum:
      name: dhcp
      state: absent
  when:
      - not rhel7cis_dhcp_server
      - rhel7cis_rule_2_2_5|bool
  tags:
      - level1
      - scored
      - dhcp
      - services
      - patch
      - rule_2.2.5

- name: "SCORED | 2.2.6 | PATCH | Ensure LDAP server is not installed"
  yum:
      name: openldap-servers
      state: absent
  when:
      - not rhel7cis_ldap_server
      - rhel7cis_rule_2_2_6|bool
  tags:
      - level1
      - scored
      - ldap
      - services
      - patch
      - rule_2.2.6

- name: "SCORED | 2.2.7 | PATCH | Ensure nfs-utils is not installed or the nfs-server service is masked"
  yum:
      name: nfs-utils
      state: absent
  when:
      - not rhel7cis_nfs_rpc_server
      - rhel7cis_rule_2_2_7|bool
  tags:
      - level1
      - scored
      - nfs
      - rpc
      - services
      - patch
      - rule_2.2.7

- name: "SCORED | 2.2.8 | PATCH | Ensure rpcbind is not installed or the rpcbind services are masked"
  yum:
      name: rpcbind
      state: absent
  when:
      - not rhel7cis_nfs_rpc_server
      - rhel7cis_rule_2_2_7|bool
  tags:
      - level1
      - scored
      - nfs
      - rpc
      - services
      - patch
      - rule_2.2.8

- name: "SCORED | 2.2.9 | PATCH | Ensure DNS Server is not installed"
  yum:
      name: bind
      state: absent
  when:
      - not rhel7cis_named_server
      - rhel7cis_rule_2_2_9|bool
  tags:
      - level1
      - patch
      - rule_2.2.9

- name: "SCORED | 2.2.10 | PATCH | Ensure FTP Server is not installed"
  yum:
      name: vsftpd
      state: absent
  when:
      - not rhel7cis_vsftpd_server
      - rhel7cis_rule_2_2_10|bool
  tags:
      - level1
      - patch
      - rule_2.2.10

- name: "SCORED | 2.2.11 | PATCH | Ensure HTTP server is not installed"
  yum:
      name: httpd
      state: absent
  when:
      - not rhel7cis_httpd_server
      - rhel7cis_rule_2_2_11|bool
  tags:
      - level1
      - patch
      - rule_2.2.11

- name: "SCORED | 2.2.12 | PATCH | Ensure IMAP and POP3 server is not installed"
  yum:
      name: dovecot
      state: absent
  when:
      - not rhel7cis_dovecot_server
      - rhel7cis_rule_2_2_12|bool
  tags:
      - level1
      - patch
      - rule_2.2.12

- name: "SCORED | 2.2.13 | PATCH | Ensure Samba is not installed"
  yum:
      name: samba
      state: absent
  when:
      - not rhel7cis_smb_server
      - rhel7cis_rule_2_2_13|bool
  tags:
      - level1
      - patch
      - rule_2.2.13

- name: "SCORED | 2.2.14 | PATCH | Ensure HTTP Proxy Server is not installed"
  yum:
      name: squid
      state: absent
  when:
      - not rhel7cis_squid_server
      - rhel7cis_rule_2_2_14|bool
  tags:
      - level1
      - patch
      - rule_2.2.14

- name: "SCORED | 2.2.15 | PATCH | Ensure SNMP Server is not installed"
  yum:
      name: net-snmp
      state: absent
  when:
      - not rhel7cis_snmp_server
      - rhel7cis_rule_2_2_15|bool
  tags:
      - level1
      - patch
      - rule_2.2.15

- name: "SCORED | 2.2.16 | PATCH | Ensure mail transfer agent is configured for local-only mode"
  lineinfile:
      dest: /etc/postfix/main.cf
      regexp: "^(#)?inet_interfaces"
      line: "inet_interfaces = loopback-only"
  notify:
      - restart postfix
  when:
      - not rhel7cis_is_mail_server
      - postfix_installed.rc == 0
      - rhel7cis_rule_2_2_16|bool
  tags:
      - level1
      - patch
      - rule_2.2.16

- name: "SCORED | 2.2.17 | PATCH | Ensure rsync service is not installed"
  yum:
      name: rsync
      state: absent
  when:
      - not rhel7cis_rsyncd_server
      - rhel7cis_rule_2_2_17|bool
  tags:
      - level1
      - patch
      - rule_2.2.17

- name: "SCORED | 2.2.18 | PATCH | Ensure NIS Server is not installed"
  yum:
      name: ypserv
      state: absent
  when:
      - not rhel7cis_nis_server
      - rhel7cis_rule_2_2_18|bool
  tags:
      - level1
      - patch
      - rule_2.2.18

- name: "SCORED | 2.2.19 | PATCH | Ensure telnet-server is not installed"
  yum:
      name: telnet-server
      state: absent
  when:
      - not rhel7cis_telnet_server
      - rhel7cis_rule_2_2_19|bool
  tags:
      - level1
      - patch
      - rule_2.2.19

- name: "SCORED | 2.3.1 | PATCH | Ensure NIS Client is not installed"
  yum:
      name: ypbind
      state: absent
  when:
      - not rhel7cis_ypbind_required
      - rhel7cis_rule_2_3_1|bool
  tags:
      - level1
      - patch
      - rule_2.3.1

- name: "SCORED | 2.3.2 | PATCH | Ensure rsh client is not installed"
  yum:
      name: rsh
      state: absent
  when:
      - not rhel7cis_rsh_required
      - rhel7cis_rule_2_3_2|bool
  tags:
      - level1
      - patch
      - rule_2.3.2

- name: "SCORED | 2.3.3 | PATCH | Ensure talk client is not installed"
  yum:
      name: talk
      state: absent
  when:
      - not rhel7cis_talk_required
      - rhel7cis_rule_2_3_3|bool
  tags:
      - level1
      - patch
      - rule_2.3.3

- name: "SCORED | 2.3.4 | PATCH | Ensure telnet client is not installed"
  yum:
      name: telnet
      state: absent
  when:
      - not rhel7cis_talk_required
      - rhel7cis_rule_2_3_4|bool
  tags:
      - level1
      - patch
      - rule_2.3.4

- name: "SCORED | 2.3.5 | PATCH | Ensure LDAP client is not installed"
  yum:
      name: openldap-clients
      state: absent
  when:
      - not rhel7cis_openldap_clients_required
      - rhel7cis_rule_2_3_5|bool
  tags:
      - level1
      - patch
      - rule_2.3.5

- name: "NOTSCORED | 2.4 | PATCH |  Ensure nonessential services are removed or masked"
  command: /bin/true
  changed_when: no
  when:
      - rhel7cis_rule_2_4|bool
  tags:
      - level1
      - patch
      - notscored
      - rule_2.4
      - notimplemented
